VIDEO_DESCRIPTION_MAP = {
    "Interactive_Trading_Screen.mp4": """The image depicts a man standing in front of a large, interactive screen displaying a trading interface. He is dressed in a white shirt and has his back to the camera, with his right arm extended toward the screen as if he is interacting with it. The screen shows a detailed financial trading dashboard, featuring a candlestick chart that likely represents the price movement of a financial asset over time. Surrounding the chart are various lists and numerical data with columns highlighted in different colors, possibly showing different assets, price values, changes, and other trading metrics. The interface is highly detailed, indicating a sophisticated trading or financial analysis application, suggesting that the environment might be a trading room or an analytical setting.""",
    "Stock_Data_Visualization.mp4": """The video frame illustrates a dynamic stock market analysis visualization. It prominently features a curving green line graph displaying financial data trends over time, with specific data points marked and labeled with values like "0.78901" and "0.01234." Adjacent to the line graph are tall, 3D bar graphs, potentially representing volumes or comparative financial figures. The background of the video includes a dark grid pattern overlaid with a matrix of glowing dots, emphasizing a high-tech, digital aesthetic. Overlay lines and geometric shapes add to the impression of an advanced analytical interface, suggesting a focus on tracking and analyzing market movements.""",
    "Stock_App_Interaction.mp4":"""The video shows a person holding a smartphone, displaying a stock trading app. The phone is encased in a red cover, and the screen features a financial application with a green line graph indicating upward movement or growth in stock value. The application shows a balance of "Investing $891.59" at the top, suggesting the current portfolio value. The interface contains various icons and options for navigating the app and reviewing other financial details. The person's hands, slightly tattooed, are actively interacting with the app, possibly navigating through different features. The background is a blurred indoor setting, highlighting the focus on the smartphone and the application in use.""",
    "Stock_Price_Display.mp4":
        """
The video frame focuses on a digital display showing stock price information. Prominently featured is a red numerical value "23.299" followed by a downward red arrow, suggesting a decrease in price. Next to it, "$23.30" is displayed in blue, likely indicating the current price or a different financial metric. Below, there are additional numbers in green, such as "23.299" and "23.296," possibly representing other stock prices or metrics associated with positive movements. The overall design and color scheme convey a real-time stock market interface, commonly used for tracking market fluctuations.       
""",
    "Trader_Stress_Reaction.mp4":
        """
The video captures a moment in a financial analysis setting, where a man in a white shirt is seated at a desk, looking stressed or deep in thought. He has one hand on his head and holds a pair of glasses in the other, suggesting concern or contemplation. In the background, a large screen displays a complex trading interface, filled with candlestick charts, numerical data, and market metrics, reflecting an active trading or financial analysis environment. The scene communicates the challenges and intensity often associated with stock market trading.
""",
    "Stock_Chart_Analysis.mp4":
        """
The video highlights a detailed analysis session where financial charts are laid out on a table. A hand is holding a magnifying glass over printed pages, closely examining stock market charts. The charts display candlestick patterns and trend lines, indicating detailed scrutiny of price movements and technical analysis. Surrounding the primary charts are various sheets with colorful graphs and data, suggesting a comprehensive approach to understanding market trends and making informed decisions. The scene emphasizes meticulous attention to financial details and analysis for stock trading or investment strategies.
""",
    "Profit_Trend_Illustration.mp4":
        """
The video illustrates a simplified representation of financial profit fluctuations. It features a line graph with a bold blue zigzagging line, marked with red circular points at each peak and trough. Along the graph, symbols depicting euro currency coins are positioned near these key points, highlighting areas of interest regarding profit levels. The word "PROFIT" is prominently displayed at the top, indicating the focus of the visual representation. The overall design is clean and conceptual, aimed at conveying basic concepts about profit cycles or trends in financial contexts.
""",
    "Market_Downturn_Graph.mp4":
        """
The video presents a dramatic visualization of stock market decline. It features red line graphs and candlestick charts set against a red grid background, indicating falling stock prices or negative market trends. The downward trajectory is emphasized by sharp angles in the line graph and red downward arrows, suggesting bearish market conditions. The intense red color scheme conveys urgency and highlights the theme of financial downturn. This kind of visualization is typically used to depict periods of significant market losses or corrections.
""",
    "Stock_Ticker_Grid.mp4":
        """
The video displays a dynamic grid of numerical data, reminiscent of a stock ticker board or a financial data matrix. The numbers are arranged in rows and columns, and are color-coded in white, red, and yellow, possibly to signify different market statuses or changes. The colors likely represent various conditions such as gains, losses, or neutral positions in stock prices or indices. This kind of colorful, fast-moving data presentation is typical in financial environments to convey real-time market information quickly and efficiently.""",

}
